dist: xenial
language: node_js
  - "node"
  # ^ use latest version of NodeJS

# Unless we specify "sudo: false", build runs in VM, not container

# Limit the number of commits it will clone
git:
  depth: 3

# Only do CI for the default branch
branches:
  only:
  - latestRelease

before_install:
  - export PATH=$HOME/bin:$PATH
  # ^ Include the folder that will store the "dhall-to-json" binary on PATH

install:
  - npm i -g purescript@0.12.5 spago
  # ^ Use NPM to install most packages
  - chmod +x .travis/spago--print-versions.sh
  - ./.travis/spago--print-versions.sh
  # ^ Crudely print installed packages' versions
  - chmod +x .travis/spago--install.sh
  - ./.travis/spago--install.sh
  # ^ Install each folder's contents using custom script

before_script:
  - chmod +x .travis/spago--build-and-test.sh

script:
  - ./.travis/spago--build-and-test.sh

cache:
  directories:
    - 11-Syntax/01-Basic-Syntax/.spago
    - 11-Syntax/01-Basic-Syntax/output
    - 11-Syntax/02-Foreign-Function-Interface/.spago
    - 11-Syntax/02-Foreign-Function-Interface/output
    - 11-Syntax/03-Type-Level-Programming-Syntax/.spago
    - 11-Syntax/03-Type-Level-Programming-Syntax/output
    - 11-Syntax/04-Module-Syntax/.spago
    - 11-Syntax/04-Module-Syntax/output
    - 11-Syntax/05-Prelude-Syntax/.spago
    - 11-Syntax/05-Prelude-Syntax/output
    - 21-Hello-World/03-Hello-World-and-Effects/.spago
    - 21-Hello-World/03-Hello-World-and-Effects/output
    - 21-Hello-World/04-Debugging/.spago
    - 21-Hello-World/04-Debugging/output
    - 21-Hello-World/05-Testing/.spago
    - 21-Hello-World/05-Testing/output
    - 21-Hello-World/06-Benchmarking/.spago
    - 21-Hello-World/06-Benchmarking/output
    - 21-Hello-World/06-Benchmarking/node_modules
    - 21-Hello-World/07-Type-Level-Programming/.spago
    - 21-Hello-World/07-Type-Level-Programming/output
    - 21-Hello-World/08-Application-Structure/.spago
    - 21-Hello-World/08-Application-Structure/output
    - 22-Projects/.spago
    - 22-Projects/output
    - 22-Projects/node_modules
