dist: xenial
language: minimal
  # Use `nvm` to install latest version of NodeJS

# Unless we specify "sudo: false", build runs in VM, not container

# Limit the number of commits it will clone
git:
  depth: 3

# Only do CI for the default branch
branches:
  only:
  - latestRelease

before_install:
  - nvm install node
  # ^ Install latest version of Node
  - npm i -g npm
  # ^ Update NPM

install:
  - npm i -g purescript@0.13.6 spago@0.13.0
  # ^ Use NPM to install most packages
  - chmod +x .travis/spago--print-versions.sh
  - ./.travis/spago--print-versions.sh
  # ^ Crudely print installed packages' versions
  - chmod +x .travis/spago--install.sh
  - ./.travis/spago--install.sh
  # ^ Install each folder's contents using custom script

before_script:
  - chmod +x .travis/spago--build-and-test.sh

script:
  - ./.travis/spago--build-and-test.sh

cache:
  directories:
    - 11-Syntax/01-Basic-Syntax/.spago
    - 11-Syntax/02-Foreign-Function-Interface/.spago
    - 11-Syntax/03-Type-Level-Programming-Syntax/.spago
    - 11-Syntax/04-Module-Syntax/.spago
    - 11-Syntax/05-Prelude-Syntax/.spago
    - 11-Syntax/06-Modifying-Do-Ado-Syntax-Sugar/.spago
    - 21-Hello-World/02-Effect-and-Aff/.spago
    - 21-Hello-World/03-Debugging/.spago
    - 21-Hello-World/04-Foldable-Traversable/.spago
    - 21-Hello-World/05-Application-Structure/.spago
    - 21-Hello-World/06-Type-Level-Programming/.spago
    - 21-Hello-World/07-Testing/.spago
    - 21-Hello-World/06-Benchmarking/.spago
    - 21-Hello-World/06-Benchmarking/node_modules
    - 22-Projects/.spago
    - 22-Projects/node_modules
